// <auto-generated />
using System;
using EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace entiframe.Migrations
{
    [DbContext(typeof(TempContext))]
    partial class TempContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30");

            modelBuilder.Entity("EF.Logins", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Identifier");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("EF.Sensors", b =>
                {
                    b.Property<int>("SensorsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoginId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoginsForeignKeys")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomNr")
                        .HasColumnType("INTEGER");

                    b.HasKey("SensorsId");

                    b.HasIndex("LoginsForeignKeys");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("EF.TempSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sensornr")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SensorsForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SensorsId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<string>("Temperaturedate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SensorsForeignKey");

                    b.ToTable("TempSensors");
                });

            modelBuilder.Entity("EF.Sensors", b =>
                {
                    b.HasOne("EF.Logins", "Logins")
                        .WithMany()
                        .HasForeignKey("LoginsForeignKeys");
                });

            modelBuilder.Entity("EF.TempSensor", b =>
                {
                    b.HasOne("EF.Sensors", "Sensors")
                        .WithMany()
                        .HasForeignKey("SensorsForeignKey");
                });
#pragma warning restore 612, 618
        }
    }
}
